# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 901142f6e8127f641854250f523e3c17cddae650b646021a03f7770db80fd3bf2fd88e5c76b7a3ebd6399944b477c65202c7596d7f85d14f6d931ce24f900eb6

test:
  secret_key_base: 0ba77ea7c3bcd21bb03b8999ed1ac4f8df70768a3d4bbf9452cffaedd86d4502bc21c3febda92f11c9923df6d2382932642022062b1e1be81e7981e1d8e14997

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
